### ISSUE TITLE
Error when trying to start.

### ISSUE THREAD

**Issue by Loloman2** [databurn-in/TorGhost#2]
Running sudo torghost -s return this:

Traceback (most recent call last):
  File "torghost.py", line 117, in <module>
    notify2.init("TorGhost")
  File "notify2.py", line 103, in init
  File "dist-packages/dbus/bus.py", line 241, in get_object
  File "dist-packages/dbus/proxies.py", line 248, in __init__
  File "dist-packages/dbus/bus.py", line 180, in activate_name_owner
  File "dist-packages/dbus/bus.py", line 278, in start_service_by_name
  File "dist-packages/dbus/connection.py", line 651, in call_blocking
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

**Comment by NandanDesai** [comment]
what's the linux distro you're using?

**Comment by Loloman2** [comment]
Ubuntu 18.04.4 LTS

**Comment by NandanDesai** [comment]
ok cool. I'll try to come up with a quick fix. Hang on

**Comment by Loloman2** [comment]
Okay! Thanks!!

**Comment by NandanDesai** [comment]
`git pull` this repo, build it and try running it again.

**Comment by Loloman2** [comment]
Now I get this :(
[21:39:43] Always check for updates using -u option
[21:39:43] Torrc file already configured
[21:39:43] Configuring DNS resolv.conf file..  [done]
[21:39:43] Stopping tor service  [done]
[21:39:43] Starting new tor daemon  [done]
[21:39:43] setting up iptables rules [done]
[21:39:43] Verifying your Tor connectivity...
[21:39:58] Some error occured while connecting to https://check.torproject.org. Error message is dumped in 'torghost.dump' file in the current directory.
[21:39:58] Something went wrong. Rolling back the process...
[21:39:58] You are not on Tor. Process was failed and rolled back.

**Comment by NandanDesai** [comment]
what's the content of torghost.dump file?

**Comment by Loloman2** [comment]
HTTPSConnectionPool(host='check.torproject.org', port=443): Max retries exceeded with url: /api/ip (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f06a42bb9d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by NandanDesai** [comment]
try running TorGhost multiple times. Tell me if you get that same error all the time

**Comment by Loloman2** [comment]
Tried it 5 times :(

**Comment by NandanDesai** [comment]
Ok. For this I need some time. I'll get back to you ASAP

**Comment by Loloman2** [comment]
Okay :)

**Comment by NandanDesai** [comment]
Hi. I'm caught up in some other work so won't be able to fix this issue anytime soon. Meanwhile, if you do want this to work, then try using [anonsurf](https://github.com/ParrotSec/anonsurf) which is similar and in fact better than TorGhost! If it does work for you then please let me know here.
